//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class addBranch
    {
        public int branchId { get; set; }
        public string branchName { get; set; }
        public string branchPhone1 { get; set; }
        public string branchAddress { get; set; }
        public string branchNTN { get; set; }
        public Nullable<bool> branchActive { get; set; }
        public Nullable<int> hoBranchId { get; set; }
    }
}
