//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class addBank
    {
        public int bankId { get; set; }
        public string bankCode { get; set; }
        public string bankName { get; set; }
        public Nullable<bool> active { get; set; }
    }
}
