//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class addCompany
    {
        public int companyId { get; set; }
        public string companyName { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string fax { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string footer1 { get; set; }
        public string footer2 { get; set; }
        public string ntn { get; set; }
        public byte[] logo1 { get; set; }
        public byte[] logo2 { get; set; }
        public string logoName1 { get; set; }
        public string logoName2 { get; set; }
    }
}
