//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class addCounter
    {
        public int counterId { get; set; }
        public string counterCode { get; set; }
        public string counterName { get; set; }
        public string counterPC { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<bool> counterEnable { get; set; }
        public Nullable<System.DateTime> addedDate { get; set; }
    }
}
