//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class addItemDetail
    {
        public int itemDetailId { get; set; }
        public Nullable<int> itemMasterId { get; set; }
        public Nullable<int> categoryId { get; set; }
        public Nullable<int> itemId { get; set; }
        public string selection { get; set; }
        public Nullable<double> quantity { get; set; }
        public Nullable<int> TotalStep { get; set; }
        public string StepName { get; set; }
        public Nullable<double> totalQuantity { get; set; }
        public Nullable<int> stepMap { get; set; }
        public string priceFrom { get; set; }
        public Nullable<double> stepPrice { get; set; }
        public Nullable<bool> isSpecial { get; set; }
        public Nullable<double> specialPrice { get; set; }
    }
}
