//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class addShift
    {
        public int shiftId { get; set; }
        public string shiftName { get; set; }
        public Nullable<bool> shiftEnable { get; set; }
        public string shortName { get; set; }
    }
}
