//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class addWaiter
    {
        public int waiterId { get; set; }
        public string waiterCode { get; set; }
        public string waiterName { get; set; }
        public Nullable<bool> waiterActive { get; set; }
        public Nullable<System.DateTime> addedDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public Nullable<bool> isRider { get; set; }
        public string mobile { get; set; }
        public Nullable<bool> commissionOnPercent { get; set; }
        public Nullable<double> commsionValue { get; set; }
    }
}
