//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class areaLandMark
    {
        public int areaLandMarkId { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public string landMarkName { get; set; }
        public string prefix { get; set; }
        public int cityAreaId { get; set; }
        public System.DateTime addedDate { get; set; }
    
        public virtual cityArea cityArea { get; set; }
    }
}
