//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashInOut
    {
        public int cashInOutId { get; set; }
        public Nullable<int> counterId { get; set; }
        public string cashInOutType { get; set; }
        public string voucherNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> permissionUserId { get; set; }
        public Nullable<double> amount { get; set; }
        public string description { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public Nullable<int> shiftId { get; set; }
        public Nullable<int> customerId { get; set; }
    }
}
