//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerAddress
    {
        public int addressid { get; set; }
        public Nullable<int> customerId { get; set; }
        public string address { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> area { get; set; }
        public string landmark { get; set; }
    }
}
