//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dayMaster
    {
        public int dayId { get; set; }
        public string dayNumber { get; set; }
        public string dayName { get; set; }
        public Nullable<System.DateTime> openDate { get; set; }
        public string openTime { get; set; }
        public Nullable<int> dayOpenId { get; set; }
        public Nullable<int> dayCloseId { get; set; }
        public Nullable<System.DateTime> closeDate { get; set; }
        public string closeTime { get; set; }
        public Nullable<bool> dayActive { get; set; }
    }
}
