//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class discountDetail
    {
        public int discountDetailId { get; set; }
        public Nullable<int> discountId { get; set; }
        public string detailName { get; set; }
        public Nullable<bool> isPercent { get; set; }
        public Nullable<double> value { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> autoApply { get; set; }
        public Nullable<double> cashBack { get; set; }
    }
}
