//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class focDetail
    {
        public int focId { get; set; }
        public string orderTrackingId { get; set; }
        public string focCareOff { get; set; }
        public string focCustomer { get; set; }
    }
}
