//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBPOS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class webOrderDBEntities : DbContext
    {
        public webOrderDBEntities()
            : base("name=webOrderDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<addCategory> addCategory { get; set; }
        public virtual DbSet<addDepartment> addDepartment { get; set; }
        public virtual DbSet<addItem> addItem { get; set; }
        public virtual DbSet<addShift> addShift { get; set; }
        public virtual DbSet<areaLandMark> areaLandMark { get; set; }
        public virtual DbSet<CashInOut> CashInOut { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<cityArea> cityArea { get; set; }
        public virtual DbSet<loginUser> loginUser { get; set; }
        public virtual DbSet<orderMaster> orderMaster { get; set; }
        public virtual DbSet<ReservationDetail> ReservationDetail { get; set; }
        public virtual DbSet<ReservationMaster> ReservationMaster { get; set; }
        public virtual DbSet<timeSlot> timeSlot { get; set; }
        public virtual DbSet<addBank> addBank { get; set; }
        public virtual DbSet<addBranch> addBranch { get; set; }
        public virtual DbSet<addCompany> addCompany { get; set; }
        public virtual DbSet<addCounter> addCounter { get; set; }
        public virtual DbSet<addCustomer> addCustomer { get; set; }
        public virtual DbSet<addDealStep> addDealStep { get; set; }
        public virtual DbSet<addDeliveryCharges> addDeliveryCharges { get; set; }
        public virtual DbSet<addItemComment> addItemComment { get; set; }
        public virtual DbSet<addItemDetail> addItemDetail { get; set; }
        public virtual DbSet<addLocation> addLocation { get; set; }
        public virtual DbSet<addPaymentType> addPaymentType { get; set; }
        public virtual DbSet<addReason> addReason { get; set; }
        public virtual DbSet<addStatus> addStatus { get; set; }
        public virtual DbSet<addTable> addTable { get; set; }
        public virtual DbSet<addTax> addTax { get; set; }
        public virtual DbSet<addWaiter> addWaiter { get; set; }
        public virtual DbSet<cashDrawerLog> cashDrawerLog { get; set; }
        public virtual DbSet<customerAddress> customerAddress { get; set; }
        public virtual DbSet<dayCounter> dayCounter { get; set; }
        public virtual DbSet<dayMaster> dayMaster { get; set; }
        public virtual DbSet<dayShift> dayShift { get; set; }
        public virtual DbSet<discountDetail> discountDetail { get; set; }
        public virtual DbSet<discountMaster> discountMaster { get; set; }
        public virtual DbSet<discountUser> discountUser { get; set; }
        public virtual DbSet<focDetail> focDetail { get; set; }
        public virtual DbSet<itemCommentDetail> itemCommentDetail { get; set; }
        public virtual DbSet<itemLedger> itemLedger { get; set; }
        public virtual DbSet<itemTopping> itemTopping { get; set; }
        public virtual DbSet<logMaster> logMaster { get; set; }
        public virtual DbSet<makeFixedDeal> makeFixedDeal { get; set; }
        public virtual DbSet<makeOnDemandDeal> makeOnDemandDeal { get; set; }
        public virtual DbSet<orderDealDetail> orderDealDetail { get; set; }
        public virtual DbSet<orderDetail> orderDetail { get; set; }
        public virtual DbSet<orderFixedDealDetail> orderFixedDealDetail { get; set; }
        public virtual DbSet<orderGroup> orderGroup { get; set; }
        public virtual DbSet<orderItemCommentDetail> orderItemCommentDetail { get; set; }
        public virtual DbSet<orderItemTransfer> orderItemTransfer { get; set; }
        public virtual DbSet<orderLess> orderLess { get; set; }
        public virtual DbSet<orderOnDemandDealDetail> orderOnDemandDealDetail { get; set; }
        public virtual DbSet<orderSubgroup> orderSubgroup { get; set; }
        public virtual DbSet<partyLedger> partyLedger { get; set; }
        public virtual DbSet<rights> rights { get; set; }
        public virtual DbSet<rightsAllocated> rightsAllocated { get; set; }
        public virtual DbSet<salePayment> salePayment { get; set; }
        public virtual DbSet<setting_parameters> setting_parameters { get; set; }
        public virtual DbSet<settingCategoryToCounter> settingCategoryToCounter { get; set; }
        public virtual DbSet<settingCounterOrderType> settingCounterOrderType { get; set; }
        public virtual DbSet<settingDeliveryCharges> settingDeliveryCharges { get; set; }
        public virtual DbSet<settingPrinter> settingPrinter { get; set; }
        public virtual DbSet<settingServiceCharges> settingServiceCharges { get; set; }
        public virtual DbSet<srDetail> srDetail { get; set; }
        public virtual DbSet<srMaster> srMaster { get; set; }
        public virtual DbSet<tempSlipOrderDealDetail> tempSlipOrderDealDetail { get; set; }
        public virtual DbSet<tempSlipOrderDetail> tempSlipOrderDetail { get; set; }
        public virtual DbSet<tempSlipOrderMaster> tempSlipOrderMaster { get; set; }
        public virtual DbSet<userType> userType { get; set; }
    }
}
