//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderSubgroup
    {
        public int orderSubGroupId { get; set; }
        public Nullable<int> orderGroupId { get; set; }
        public string subgroupName { get; set; }
        public Nullable<bool> groupActive { get; set; }
        public Nullable<double> commissionPercent { get; set; }
        public Nullable<bool> receivable { get; set; }
        public Nullable<bool> isDefault { get; set; }
    }
}
