//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderLess
    {
        public int orderLessId { get; set; }
        public string orderTrackingId { get; set; }
        public Nullable<int> itemId { get; set; }
        public Nullable<int> categoryId { get; set; }
        public Nullable<int> counterId { get; set; }
        public Nullable<double> quantity { get; set; }
        public Nullable<double> tax { get; set; }
        public Nullable<double> totalAmount { get; set; }
        public string lessReason { get; set; }
        public string lesstime { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<bool> isUpload { get; set; }
        public Nullable<bool> isPrint { get; set; }
        public Nullable<int> deviceId { get; set; }
        public Nullable<int> orderDetailId { get; set; }
    }
}
