//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderOnDemandDealDetail
    {
        public int incId { get; set; }
        public string orderTrackingId { get; set; }
        public int orderDetailId { get; set; }
        public Nullable<int> onDemandDealId { get; set; }
        public Nullable<double> dealPrice { get; set; }
        public Nullable<int> categoryId { get; set; }
        public Nullable<int> itemId { get; set; }
        public Nullable<double> itemQuantity { get; set; }
        public Nullable<double> totalQuantity { get; set; }
        public string comments { get; set; }
        public Nullable<System.DateTime> addedDate { get; set; }
    }
}
