//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderItemTransfer
    {
        public int transferId { get; set; }
        public Nullable<System.DateTime> tDate { get; set; }
        public string tTime { get; set; }
        public string prvOrderId { get; set; }
        public string newOrderId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> shiftId { get; set; }
        public Nullable<int> counterId { get; set; }
        public Nullable<int> tiltId { get; set; }
        public Nullable<int> itemId { get; set; }
        public Nullable<double> quantity { get; set; }
    }
}
