//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class settingServiceCharges
    {
        public int keyId { get; set; }
        public string applyOn { get; set; }
        public Nullable<double> coverAmount { get; set; }
        public string charges { get; set; }
        public Nullable<bool> @fixed { get; set; }
        public Nullable<bool> active { get; set; }
    }
}
