//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class settingDeliveryCharges
    {
        public Nullable<double> deliveryCharges { get; set; }
        public Nullable<double> amountBelow { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<bool> active { get; set; }
        public int pkId { get; set; }
    }
}
