//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class settingCounterOrderType
    {
        public Nullable<int> counterId { get; set; }
        public string orderType { get; set; }
        public Nullable<bool> assign { get; set; }
        public int autoId { get; set; }
    }
}
