//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class srDetail
    {
        public int srDetailId { get; set; }
        public Nullable<int> srId { get; set; }
        public Nullable<int> categoryId { get; set; }
        public Nullable<int> itemId { get; set; }
        public Nullable<double> qty { get; set; }
        public Nullable<double> rate { get; set; }
        public Nullable<double> tax { get; set; }
        public Nullable<double> discount { get; set; }
        public Nullable<bool> foc { get; set; }
        public Nullable<double> totalAmount { get; set; }
        public Nullable<int> orderDetailId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<System.DateTime> returnDate { get; set; }
    }
}
