//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class srMaster
    {
        public int srId { get; set; }
        public Nullable<System.DateTime> srDate { get; set; }
        public string srTIme { get; set; }
        public string srNum { get; set; }
        public string orderType { get; set; }
        public string orderTrackingId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> shiftId { get; set; }
        public Nullable<int> counterId { get; set; }
        public Nullable<double> totalAmount { get; set; }
        public Nullable<double> tax { get; set; }
        public Nullable<double> discount { get; set; }
        public Nullable<double> sc { get; set; }
        public Nullable<double> ec { get; set; }
        public string reason { get; set; }
        public Nullable<bool> completeReturn { get; set; }
        public Nullable<int> tiltId { get; set; }
    }
}
