//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class timeSlot
    {
        public int timeSlotId { get; set; }
        public string timeSlot1 { get; set; }
        public System.DateTime timeStart { get; set; }
        public System.DateTime timeEnd { get; set; }
    }
}
